### ISSUE TITLE
When there is a dialog element, the color picker box displays behind it

### ISSUE THREAD

**Issue by tranthanhhoang060391** [sefianecho/alwan#17]
Hi,

Thank you for your great work!

Recently, I tried to set up a library in a dialog element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog), whenever I click a button color, the color picker shows up behind the dialog

<img width="710" alt="Screenshot 2024-04-16 at 21 32 37" src="https://github.com/sefianecho/alwan/assets/9476360/bb6b961c-fa4d-40e6-a937-cf7b497d1742">

<img width="714" alt="Screenshot 2024-04-16 at 21 32 48" src="https://github.com/sefianecho/alwan/assets/9476360/b292380c-2162-4598-9cdc-b56af621fbbd">

I believe the cause is the Top Layer (https://developer.mozilla.org/en-US/docs/Glossary/Top_layer)

I tried to move the `<div class="alwan" ... ></div>` inside the `dialog`, it does help to display the color picker panel above the dialog element but the position of the picker panel is incorrect ( the `transform: translate ` CSS)

<img width="1683" alt="Screenshot 2024-04-16 at 21 48 20" src="https://github.com/sefianecho/alwan/assets/9476360/4c489c8d-cf0a-4d51-b7fb-6cb3f9af6f0d">

Thank you so much for your supporting

**Comment by sefianecho** [comment]
Hi,
I understand the problem, it's a little bit complicated but I will try to fix it as soon as possible.

**Comment by apeisa** [comment]
Any news regarding this? Would you accept PR:s?

PS: @sefianecho do you take sponsors or any other means to support your great work with this? We use it a lot on our Saas platform and it would be great to support your project somehow.
