### ISSUE TITLE
How to use a shadow DOM element as the reference element?

### ISSUE THREAD

**Issue by RajeshKumarS** [sefianecho/alwan#19]
I would like to use Alwan color picker inside within a custom web component. One of the shadow DOM element has to be used as the reference element. Is it possible and if so, how to pass the reference element (as the 1st argument)?

**Comment by sefianecho** [comment]
It should be fixed now.
You can set the reference element as a shadow DOM element.
```javascript
const alwan = new Alwan(shadowRoot.querySelector('reference-selector'));
```

**Comment by RajeshKumarS** [comment]
Thanks. It works now.

**Comment by RajeshKumarS** [comment]
Thanks. Will try.
